-- Labellisation conseiller numérique (#1776) : l'attestation sur l'honneur
-- cliquée à la fin du parcours de labellisation crée une ligne — une ligne par
-- attestation, table append-only (jamais d'UPDATE).
--
-- Migration NEUTRALISÉE lors du chantier N11 (2026-08) : main.conum_labellisation
-- appartient au schéma main, porté par Flyway côté dataspace (V143, 2026-08-12).
-- Depuis la régénération du snapshot dataspace_integration (postérieure à V143),
-- la table, ses index et ses FK arrivent déjà par le snapshot — recréer ici
-- ferait échouer le replay (42P07 already exists). La définition d'origine
-- reste dans l'historique git de ce fichier.
SELECT 1;
