version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "eslint*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: "@stylistic/eslint-plugin"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
