services:
  postgres:
    image: postgres:15.8-alpine # Conserver la même version avec celle de Scalingo
    environment:
      POSTGRES_DB: sgn
      POSTGRES_USER: sgn
      POSTGRES_PASSWORD: sgn
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=30"]
    healthcheck:
      test: pg_isready -U sgn
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
