services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_DB: min
      POSTGRES_USER: min
      POSTGRES_PASSWORD: min
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=30"]
    healthcheck:
      test: pg_isready -U min
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
