services:
  postgres-dev:
    extends:
      file: common-services.yml
      service: postgres
    container_name: min_db_dev
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  postgres-test:
    extends:
      file: common-services.yml
      service: postgres
    container_name: min_db_test
    ports:
      - target: 5432
        published: 5434
    volumes:
      - type: volume
        source: postgres_data_test
        target: /var/lib/postgresql/data

  mailpit-dev:
    extends:
      file: common-services.yml
      service: mailpit
    container_name: min_mailpit_dev
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - type: volume
        source: mailpit_data_dev
        target: /data

volumes:
  postgres_data:
  postgres_data_test:
  mailpit_data_dev:
