services:
  postgres-dev:
    extends:
      file: common-services.yml
      service: postgres
    container_name: min_db_dev
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./dbs
        target: /dbs

  postgres-test:
    extends:
      file: common-services.yml
      service: postgres
    container_name: min_db_test
    ports:
      - target: 5432
        published: 5434
    volumes:
      - type: volume
        source: postgres_data_test
        target: /var/lib/postgresql/data

  mailpit-dev:
    extends:
      file: common-services.yml
      service: mailpit
    container_name: min_mailpit_dev
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - type: volume
        source: mailpit_data_dev
        target: /data

  minio:
    image: minio/minio:latest
    container_name: min_minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - type: volume
        source: minio_data
        target: /data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  postgres_data_test:
  mailpit_data_dev:
  minio_data:
