DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'sonum') THEN

      RAISE NOTICE 'Role "sonum" already exists. Skipping.';
   ELSE
      CREATE ROLE sonum LOGIN PASSWORD 'my_password';
   END IF;
END
$do$;


DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'app_python') THEN

      RAISE NOTICE 'Role "app_python" already exists. Skipping.';
   ELSE
      CREATE ROLE app_python LOGIN PASSWORD 'my_password';
   END IF;
END
$do$;

DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'min_dev') THEN

      RAISE NOTICE 'Role "min_dev" already exists. Skipping.';
   ELSE
      CREATE ROLE min_dev  LOGIN PASSWORD 'my_password';
   END IF;
END
$do$;

DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'min_scalingo') THEN

      RAISE NOTICE 'Role "min_scalingo" already exists. Skipping.';
   ELSE
      CREATE ROLE min_scalingo  LOGIN PASSWORD 'my_password';
   END IF;
END
$do$;

--
-- Name: admin; Type: SCHEMA; Schema: -; Owner: sonum
--

CREATE SCHEMA IF NOT EXISTS admin;


ALTER SCHEMA admin OWNER TO sonum;

--
-- Name: main; Type: SCHEMA; Schema: -; Owner: sonum
--

CREATE SCHEMA IF NOT EXISTS main;


ALTER SCHEMA main OWNER TO sonum;

--
-- Name: reference; Type: SCHEMA; Schema: -; Owner: sonum
--

CREATE SCHEMA IF NOT EXISTS reference;


ALTER SCHEMA reference OWNER TO sonum;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA min;


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

--
-- Name: commune; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.commune (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon) NOT NULL,
    departement_id integer NOT NULL,
    statut character varying(24),
    code_insee character varying(5) NOT NULL,
    nom character varying(50) NOT NULL,
    population integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.commune OWNER TO sonum;

--
-- Name: commune_epci; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.commune_epci (
    id integer NOT NULL,
    commune_id integer NOT NULL,
    epci_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.commune_epci OWNER TO sonum;

--
-- Name: departement; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.departement (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon) NOT NULL,
    region_id integer NOT NULL,
    code character varying(3) NOT NULL,
    nom character varying(30) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.departement OWNER TO sonum;

--
-- Name: epci; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.epci (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon) NOT NULL,
    code character varying(9) NOT NULL,
    type character varying(32) NOT NULL,
    nom character varying(90) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.epci OWNER TO sonum;

--
-- Name: region; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.region (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon) NOT NULL,
    code character varying(2) NOT NULL,
    nom character varying(35) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.region OWNER TO sonum;

--
-- Name: coll_terr; Type: MATERIALIZED VIEW; Schema: admin; Owner: sonum
--

CREATE MATERIALIZED VIEW admin.coll_terr AS
 SELECT region.id AS region_id,
    region.code AS region_code,
    region.nom AS region_nom,
    departement.id AS departement_id,
    departement.code AS departement_code,
    departement.nom AS departement_nom,
    epci.code AS epci_code,
    epci.type AS epci_type,
    epci.nom AS epci_nom,
    commune.id AS commune_id,
    commune.code_insee,
    commune.nom AS commune_nom
   FROM ((((admin.commune
     LEFT JOIN admin.commune_epci ON ((commune.id = commune_epci.commune_id)))
     LEFT JOIN admin.epci ON ((epci.id = commune_epci.epci_id)))
     LEFT JOIN admin.departement ON ((departement.id = commune.departement_id)))
     LEFT JOIN admin.region ON ((region.id = departement.region_id)))
  WITH NO DATA;


ALTER MATERIALIZED VIEW admin.coll_terr OWNER TO sonum;

--
-- Name: commune_epci_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.commune_epci ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.commune_epci_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commune_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.commune ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.commune_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departement_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.departement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.departement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: epci_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.epci ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.epci_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ifn_commune; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.ifn_commune (
    id integer NOT NULL,
    code_insee character varying(5) NOT NULL,
    score numeric,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.ifn_commune OWNER TO sonum;

--
-- Name: TABLE ifn_commune; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON TABLE admin.ifn_commune IS 'Table de gestion des communes IFN - Indice de Fragilité Numérique : https://fragilite-numerique.fr/';


--
-- Name: COLUMN ifn_commune.code_insee; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.ifn_commune.code_insee IS 'Code INSEE de la commune.';


--
-- Name: COLUMN ifn_commune.score; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.ifn_commune.score IS 'Score : Un nombre réel qui varie de [0 - 10] indiquant l''indice de fragilité numérique de la commune. cette valeur est une somme totale de plusieurs indicateurs, pour plus d''informations, voir le site : https://infos.fragilite-numerique.fr/ressources-cgu';


--
-- Name: ifn_commune_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.ifn_commune ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.ifn_commune_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insee_cp; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.insee_cp (
    id integer NOT NULL,
    code_insee character varying(5) NOT NULL,
    code_postal character varying(5) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.insee_cp OWNER TO sonum;

--
-- Name: insee_cp_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.insee_cp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.insee_cp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insee_historique; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.insee_historique (
    id integer NOT NULL,
    code_insee_ancien character varying(5) NOT NULL,
    code_insee_nouveau character varying(5) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.insee_historique OWNER TO sonum;

--
-- Name: insee_historique_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.insee_historique ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.insee_historique_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: region_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.region ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zonage; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.zonage (
    id integer NOT NULL,
    code character varying(8),
    libelle character varying(255),
    code_insee character varying(5) NOT NULL,
    type character varying(3) NOT NULL,
    commentaire text,
    geom public.geometry(MultiPolygon),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE admin.zonage OWNER TO sonum;

--
-- Name: TABLE zonage; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON TABLE admin.zonage IS 'Table de gestion des zonages administratifs FRR et QPV';


--
-- Name: COLUMN zonage.code; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.zonage.code IS 'Identifiant unique du zonage concerne QPV uniquement - généré par l''API';


--
-- Name: COLUMN zonage.libelle; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.zonage.libelle IS 'Libelle du zonage concerne QPV uniquement - généré par l''API';


--
-- Name: COLUMN zonage.type; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.zonage.type IS 'Type de zonage (QPV: Quartier Prioritaire de la Ville, FRR: France Ruralités Revitalisation';


--
-- Name: COLUMN zonage.commentaire; Type: COMMENT; Schema: admin; Owner: sonum
--

COMMENT ON COLUMN admin.zonage.commentaire IS 'Commentaire sur le zonage - généré par l''API';


--
-- Name: zonage_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

ALTER TABLE admin.zonage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin.zonage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zonage_log_erreur; Type: TABLE; Schema: admin; Owner: sonum
--

CREATE TABLE admin.zonage_log_erreur (
    id integer NOT NULL,
    code_insee character varying(5),
    commentaire text,
    erreur text,
    date_erreur timestamp without time zone DEFAULT now()
);


ALTER TABLE admin.zonage_log_erreur OWNER TO sonum;

--
-- Name: zonage_log_erreur_id_seq; Type: SEQUENCE; Schema: admin; Owner: sonum
--

CREATE SEQUENCE admin.zonage_log_erreur_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE admin.zonage_log_erreur_id_seq OWNER TO sonum;

--
-- Name: zonage_log_erreur_id_seq; Type: SEQUENCE OWNED BY; Schema: admin; Owner: sonum
--

ALTER SEQUENCE admin.zonage_log_erreur_id_seq OWNED BY admin.zonage_log_erreur.id;


--
-- Name: adresse; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.adresse (
    id integer NOT NULL,
    id_adresse uuid,
    clef_interop character varying(50),
    departement character varying(3),
    code_postal character varying(5),
    nom_commune character varying(255),
    nom_voie character varying(255),
    numero_voie smallint,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    geom public.geometry(Point,4326),
    code_insee character varying(5),
    repetition character varying(10),
    code_ban uuid,
    additional_address_info jsonb
);


ALTER TABLE main.adresse OWNER TO sonum;

--
-- Name: structure; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.structure (
    id integer NOT NULL,
    siret character varying(15),
    rna character varying(10),
    nom character varying(255),
    code_activite_principale character varying(6),
    original_created_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    adresse_id integer,
    id_structure_ac uuid,
    categorie_juridique character varying(4) DEFAULT NULL::character varying,
    nb_mandats_ac integer,
    structure_id_coop uuid,
    etat_administratif character varying,
    denomination_sirene character varying,
    id_structure_tp integer,
    publique boolean,
    visible_pour_cartographie_nationale boolean,
    structure_cartographie_nationale_id character varying(255),
    typologies text[],
    presentation_resume character varying(500),
    presentation_detail text,
    contact jsonb,
    horaires character varying,
    prise_rdv character varying,
    structure_parente uuid,
    services text[],
    publics_specifiquement_adresses text[],
    prise_en_charge_specifique text[],
    frais_a_charge text[],
    dispositif_programmes_nationaux text[],
    formations_labels text[],
    autres_formations_labels text[],
    itinerance text[],
    modalites_acces text[],
    modalites_accompagnement text[],
    mediateurs_en_activite integer,
    emplois integer,
    source character varying,
    CONSTRAINT structure_siret_format_check CHECK (((siret)::text ~ '^\d{14}$'::text))
);


ALTER TABLE main.structure OWNER TO sonum;

--
-- Name: categories_juridiques; Type: TABLE; Schema: reference; Owner: sonum
--

CREATE TABLE reference.categories_juridiques (
    id integer NOT NULL,
    code character varying(4) NOT NULL,
    nom character varying(150) NOT NULL,
    niveau smallint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE reference.categories_juridiques OWNER TO sonum;

--
-- Name: personne; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.personne (
    id integer NOT NULL,
    prenom character varying(50),
    nom character varying(50),
    telephone character varying(20),
    id_aidant_connect character varying(50),
    id_conseiller_numerique character varying(50),
    original_created_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    is_active_ac boolean,
    formation_fne_ac boolean,
    profession_ac character varying,
    nb_accompagnements_ac integer,
    id_structure_ac uuid,
    emails jsonb,
    id_cn_pg integer,
    id_structure_tp integer,
    coop_id uuid,
    is_coordinateur boolean,
    is_mediateur boolean
);


ALTER TABLE main.personne OWNER TO sonum;

--
-- Name: personne_lieux_activites; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.personne_lieux_activites (
    id integer NOT NULL,
    personne_id integer NOT NULL,
    structure_id integer NOT NULL,
    structure_id_coop uuid NOT NULL,
    mediateur_id_coop uuid NOT NULL,
    en_cours boolean
);


ALTER TABLE main.personne_lieux_activites OWNER TO sonum;

--
-- Name: personne_structures_emplois; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.personne_structures_emplois (
    id integer NOT NULL,
    personne_id integer NOT NULL,
    structure_id integer NOT NULL,
    structure_id_coop uuid NOT NULL,
    mediateur_id_coop uuid NOT NULL,
    en_cours boolean
);


ALTER TABLE main.personne_structures_emplois OWNER TO sonum;

--
-- Name: activites_coop; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.activites_coop (
    id integer NOT NULL,
    type character varying(100) NOT NULL,
    mediateur_id_coop uuid NOT NULL,
    structure_id_coop uuid,
    date timestamp without time zone NOT NULL,
    duree integer NOT NULL,
    lieu_code_insee character varying(20),
    creation_coop timestamp without time zone,
    modification_coop timestamp without time zone,
    type_lieu character varying(100) NOT NULL,
    autonomie character varying(100),
    structure_de_redirection character varying(255),
    oriente_vers_structure boolean,
    precisions_demarche text,
    degre_de_finalisation_demarche character varying(50),
    titre_atelier character varying(255),
    niveau_atelier character varying(50),
    accompagnements integer DEFAULT 0 NOT NULL,
    thematiques text[],
    materiels text[],
    thematiques_demarche_administrative text[],
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    personne_id integer NOT NULL,
    coop_id uuid
);


ALTER TABLE main.activites_coop OWNER TO sonum;

--
-- Name: activites_coop_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.activites_coop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.activites_coop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adresse_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.adresse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.adresse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coordination_mediation; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.coordination_mediation (
    id integer NOT NULL,
    coordinateur_id integer NOT NULL,
    mediateur_id integer NOT NULL,
    coordination_id_coop uuid NOT NULL,
    mediateur_id_coop uuid NOT NULL,
    en_cours boolean
);


ALTER TABLE main.coordination_mediation OWNER TO sonum;

--
-- Name: coordination_mediation_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.coordination_mediation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.coordination_mediation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personne_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.personne ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.personne_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personne_lieux_activites_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.personne_lieux_activites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.personne_lieux_activites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personne_structures_emplois_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.personne_structures_emplois ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.personne_structures_emplois_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poste; Type: TABLE; Schema: main; Owner: sonum
--

CREATE TABLE main.poste (
    id integer NOT NULL,
    id_poste_conum integer NOT NULL,
    id_structure_tp integer,
    id_cn integer,
    typologie character varying(255),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    date_attribution timestamp without time zone NOT NULL,
    date_rendu_poste timestamp without time zone,
    poste_renouvele boolean,
    action_coselec character varying(255),
    etat character varying(255),
    CONSTRAINT check_etat_rendu CHECK ((NOT (((etat)::text = 'rendu'::text) AND (date_rendu_poste IS NULL)))),
    CONSTRAINT poste_etat_check CHECK (((etat)::text = ANY (ARRAY[('vacant'::character varying)::text, ('occupe'::character varying)::text, ('rendu'::character varying)::text]))),
    CONSTRAINT poste_typologie_check CHECK (((typologie)::text = ANY (ARRAY[('conum'::character varying)::text, ('coordo'::character varying)::text, ('dns'::character varying)::text])))
);


ALTER TABLE main.poste OWNER TO sonum;

--
-- Name: poste_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.poste ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.poste_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: structure_id_seq; Type: SEQUENCE; Schema: main; Owner: sonum
--

ALTER TABLE main.structure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME main.structure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_juridiques_id_seq; Type: SEQUENCE; Schema: reference; Owner: sonum
--

ALTER TABLE reference.categories_juridiques ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reference.categories_juridiques_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zonage_log_erreur id; Type: DEFAULT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.zonage_log_erreur ALTER COLUMN id SET DEFAULT nextval('admin.zonage_log_erreur_id_seq'::regclass);


--
-- Name: commune_epci commune_epci_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune_epci
    ADD CONSTRAINT commune_epci_pkey PRIMARY KEY (id);


--
-- Name: commune_epci commune_epci_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune_epci
    ADD CONSTRAINT commune_epci_ukey UNIQUE (commune_id, epci_id);


--
-- Name: commune commune_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune
    ADD CONSTRAINT commune_pkey PRIMARY KEY (id);


--
-- Name: commune commune_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune
    ADD CONSTRAINT commune_ukey UNIQUE (code_insee);


--
-- Name: departement departement_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.departement
    ADD CONSTRAINT departement_pkey PRIMARY KEY (id);


--
-- Name: departement departement_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.departement
    ADD CONSTRAINT departement_ukey UNIQUE (code);


--
-- Name: epci epci_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.epci
    ADD CONSTRAINT epci_pkey PRIMARY KEY (id);


--
-- Name: epci epci_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.epci
    ADD CONSTRAINT epci_ukey UNIQUE (code);


--
-- Name: ifn_commune ifn_commune_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.ifn_commune
    ADD CONSTRAINT ifn_commune_pkey PRIMARY KEY (id);


--
-- Name: insee_cp insee_cp_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.insee_cp
    ADD CONSTRAINT insee_cp_pkey PRIMARY KEY (id);


--
-- Name: insee_cp insee_cp_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.insee_cp
    ADD CONSTRAINT insee_cp_ukey UNIQUE (code_postal, code_insee);


--
-- Name: insee_historique insee_historique_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.insee_historique
    ADD CONSTRAINT insee_historique_pkey PRIMARY KEY (id);


--
-- Name: insee_historique insee_historique_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.insee_historique
    ADD CONSTRAINT insee_historique_ukey UNIQUE (code_insee_ancien, code_insee_nouveau);


--
-- Name: region region_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.region
    ADD CONSTRAINT region_pkey PRIMARY KEY (id);


--
-- Name: region region_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.region
    ADD CONSTRAINT region_ukey UNIQUE (code);


--
-- Name: zonage zonage_code_ukey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.zonage
    ADD CONSTRAINT zonage_code_ukey UNIQUE (code);


--
-- Name: zonage_log_erreur zonage_log_erreur_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.zonage_log_erreur
    ADD CONSTRAINT zonage_log_erreur_pkey PRIMARY KEY (id);


--
-- Name: zonage zonage_pkey; Type: CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.zonage
    ADD CONSTRAINT zonage_pkey PRIMARY KEY (id);


--
-- Name: activites_coop activites_coop_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.activites_coop
    ADD CONSTRAINT activites_coop_pkey PRIMARY KEY (id);


--
-- Name: activites_coop activites_coop_unique_coop_id; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.activites_coop
    ADD CONSTRAINT activites_coop_unique_coop_id UNIQUE (coop_id);


--
-- Name: adresse adresse_id_adresse_key; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.adresse
    ADD CONSTRAINT adresse_id_adresse_key UNIQUE (id_adresse);


--
-- Name: adresse adresse_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.adresse
    ADD CONSTRAINT adresse_pkey PRIMARY KEY (id);


--
-- Name: adresse adresse_ukey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.adresse
    ADD CONSTRAINT adresse_ukey UNIQUE (code_postal, nom_commune, nom_voie, numero_voie, repetition);


--
-- Name: coordination_mediation coordination_mediation_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.coordination_mediation
    ADD CONSTRAINT coordination_mediation_pkey PRIMARY KEY (id);


--
-- Name: personne personne_coop_id_key; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT personne_coop_id_key UNIQUE (coop_id);


--
-- Name: personne_lieux_activites personne_lieux_activites_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_lieux_activites
    ADD CONSTRAINT personne_lieux_activites_pkey PRIMARY KEY (id);


--
-- Name: personne personne_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT personne_pkey PRIMARY KEY (id);


--
-- Name: personne_structures_emplois personne_structures_emplois_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_structures_emplois
    ADD CONSTRAINT personne_structures_emplois_pkey PRIMARY KEY (id);


--
-- Name: poste poste_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.poste
    ADD CONSTRAINT poste_pkey PRIMARY KEY (id);


--
-- Name: poste poste_unique_id_poste_conum; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.poste
    ADD CONSTRAINT poste_unique_id_poste_conum UNIQUE (id_poste_conum);


--
-- Name: structure structure_id_structure_ac_unique; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT structure_id_structure_ac_unique UNIQUE (id_structure_ac);


--
-- Name: structure structure_id_structure_coop_unique; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT structure_id_structure_coop_unique UNIQUE (structure_id_coop);


--
-- Name: structure structure_pkey; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT structure_pkey PRIMARY KEY (id);


--
-- Name: personne unique_id_aidant_connect; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT unique_id_aidant_connect UNIQUE (id_aidant_connect);


--
-- Name: personne unique_id_conseiller_numerique; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT unique_id_conseiller_numerique UNIQUE (id_conseiller_numerique);


--
-- Name: personne uq_id_cn_pg; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT uq_id_cn_pg UNIQUE (id_cn_pg);


--
-- Name: poste uq_id_poste_cn_strcuture; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.poste
    ADD CONSTRAINT uq_id_poste_cn_strcuture UNIQUE (id_poste_conum, id_structure_tp, id_cn);


--
-- Name: structure uq_id_structure_tp; Type: CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT uq_id_structure_tp UNIQUE (id_structure_tp);


--
-- Name: categories_juridiques categories_juridiques_pkey; Type: CONSTRAINT; Schema: reference; Owner: sonum
--

ALTER TABLE ONLY reference.categories_juridiques
    ADD CONSTRAINT categories_juridiques_pkey PRIMARY KEY (id);


--
-- Name: categories_juridiques categories_juridiques_ukey; Type: CONSTRAINT; Schema: reference; Owner: sonum
--

ALTER TABLE ONLY reference.categories_juridiques
    ADD CONSTRAINT categories_juridiques_ukey UNIQUE (code);


--
-- Name: commune_geom_idx; Type: INDEX; Schema: admin; Owner: sonum
--

CREATE INDEX commune_geom_idx ON admin.commune USING gist (geom);


--
-- Name: commune_nom_idx; Type: INDEX; Schema: admin; Owner: sonum
--

CREATE INDEX commune_nom_idx ON admin.commune USING btree (nom);


--
-- Name: ifn_commune_code_insee_idx; Type: INDEX; Schema: admin; Owner: sonum
--

CREATE INDEX ifn_commune_code_insee_idx ON admin.ifn_commune USING btree (code_insee);


--
-- Name: zonage_code_insee_idx; Type: INDEX; Schema: admin; Owner: sonum
--

CREATE INDEX zonage_code_insee_idx ON admin.zonage USING btree (code_insee);


--
-- Name: zonage_geom_idx; Type: INDEX; Schema: admin; Owner: sonum
--

CREATE INDEX zonage_geom_idx ON admin.zonage USING gist (geom);


--
-- Name: adresse_geom_idx; Type: INDEX; Schema: main; Owner: sonum
--

CREATE INDEX adresse_geom_idx ON main.adresse USING gist (geom);

--
-- Name: commune commune_departement_id; Type: FK CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune
    ADD CONSTRAINT commune_departement_id FOREIGN KEY (departement_id) REFERENCES admin.departement(id);


--
-- Name: commune_epci commune_epci_commune_id; Type: FK CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune_epci
    ADD CONSTRAINT commune_epci_commune_id FOREIGN KEY (commune_id) REFERENCES admin.commune(id);


--
-- Name: commune_epci commune_epci_epci_id; Type: FK CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.commune_epci
    ADD CONSTRAINT commune_epci_epci_id FOREIGN KEY (epci_id) REFERENCES admin.epci(id);


--
-- Name: departement departement_region_id; Type: FK CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.departement
    ADD CONSTRAINT departement_region_id FOREIGN KEY (region_id) REFERENCES admin.region(id);


--
-- Name: zonage zonage_code_insee_fkey; Type: FK CONSTRAINT; Schema: admin; Owner: sonum
--

ALTER TABLE ONLY admin.zonage
    ADD CONSTRAINT zonage_code_insee_fkey FOREIGN KEY (code_insee) REFERENCES admin.commune(code_insee);


--
-- Name: coordination_mediation fk_coodinateur_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.coordination_mediation
    ADD CONSTRAINT fk_coodinateur_id FOREIGN KEY (coordinateur_id) REFERENCES main.personne(id);


--
-- Name: coordination_mediation fk_coordination_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.coordination_mediation
    ADD CONSTRAINT fk_coordination_id_coop FOREIGN KEY (coordination_id_coop) REFERENCES main.personne(coop_id);


--
-- Name: personne fk_id_structure_tp; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT fk_id_structure_tp FOREIGN KEY (id_structure_tp) REFERENCES main.structure(id_structure_tp);


--
-- Name: poste fk_id_structure_tp; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.poste
    ADD CONSTRAINT fk_id_structure_tp FOREIGN KEY (id_structure_tp) REFERENCES main.structure(id_structure_tp);


--
-- Name: personne_lieux_activites fk_lieu_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_lieux_activites
    ADD CONSTRAINT fk_lieu_id FOREIGN KEY (structure_id) REFERENCES main.structure(id);


--
-- Name: personne_lieux_activites fk_lieu_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_lieux_activites
    ADD CONSTRAINT fk_lieu_id_coop FOREIGN KEY (structure_id_coop) REFERENCES main.structure(structure_id_coop);


--
-- Name: coordination_mediation fk_mediateur_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.coordination_mediation
    ADD CONSTRAINT fk_mediateur_id FOREIGN KEY (mediateur_id) REFERENCES main.personne(id);


--
-- Name: coordination_mediation fk_mediateur_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.coordination_mediation
    ADD CONSTRAINT fk_mediateur_id_coop FOREIGN KEY (mediateur_id_coop) REFERENCES main.personne(coop_id);


--
-- Name: personne_structures_emplois fk_mediateur_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_structures_emplois
    ADD CONSTRAINT fk_mediateur_id_coop FOREIGN KEY (mediateur_id_coop) REFERENCES main.personne(coop_id);


--
-- Name: personne_lieux_activites fk_mediateur_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_lieux_activites
    ADD CONSTRAINT fk_mediateur_id_coop FOREIGN KEY (mediateur_id_coop) REFERENCES main.personne(coop_id);


--
-- Name: personne_structures_emplois fk_personne_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_structures_emplois
    ADD CONSTRAINT fk_personne_id FOREIGN KEY (personne_id) REFERENCES main.personne(id);


--
-- Name: personne_lieux_activites fk_personne_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_lieux_activites
    ADD CONSTRAINT fk_personne_id FOREIGN KEY (personne_id) REFERENCES main.personne(id);


--
-- Name: activites_coop fk_personne_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.activites_coop
    ADD CONSTRAINT fk_personne_id FOREIGN KEY (personne_id) REFERENCES main.personne(id);


--
-- Name: personne_structures_emplois fk_structure_id; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_structures_emplois
    ADD CONSTRAINT fk_structure_id FOREIGN KEY (structure_id) REFERENCES main.structure(id);


--
-- Name: personne_structures_emplois fk_structure_id_coop; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne_structures_emplois
    ADD CONSTRAINT fk_structure_id_coop FOREIGN KEY (structure_id_coop) REFERENCES main.structure(structure_id_coop);


--
-- Name: personne personne_id_structure_ac_fkey; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.personne
    ADD CONSTRAINT personne_id_structure_ac_fkey FOREIGN KEY (id_structure_ac) REFERENCES main.structure(id_structure_ac);


--
-- Name: structure structure_adresse_fkey; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT structure_adresse_fkey FOREIGN KEY (adresse_id) REFERENCES main.adresse(id);


--
-- Name: structure structure_categorie_juridique; Type: FK CONSTRAINT; Schema: main; Owner: sonum
--

ALTER TABLE ONLY main.structure
    ADD CONSTRAINT structure_categorie_juridique FOREIGN KEY (categorie_juridique) REFERENCES reference.categories_juridiques(code);


--
-- Name: SCHEMA admin; Type: ACL; Schema: -; Owner: sonum
--

GRANT USAGE ON SCHEMA admin TO app_python;
GRANT USAGE ON SCHEMA admin TO min_scalingo;
GRANT USAGE ON SCHEMA admin TO min_dev;


--
-- Name: SCHEMA main; Type: ACL; Schema: -; Owner: sonum
--

GRANT USAGE ON SCHEMA main TO app_python;
GRANT USAGE ON SCHEMA main TO min_scalingo;
GRANT USAGE ON SCHEMA main TO min_dev;


--
-- Name: SCHEMA reference; Type: ACL; Schema: -; Owner: sonum
--

GRANT USAGE ON SCHEMA reference TO min_scalingo;
GRANT USAGE ON SCHEMA reference TO min_dev;


--
-- Name: TABLE commune; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.commune TO app_python;
GRANT SELECT ON TABLE admin.commune TO min_scalingo;
GRANT SELECT ON TABLE admin.commune TO min_dev;


--
-- Name: TABLE commune_epci; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.commune_epci TO app_python;
GRANT SELECT ON TABLE admin.commune_epci TO min_scalingo;
GRANT SELECT ON TABLE admin.commune_epci TO min_dev;


--
-- Name: TABLE departement; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.departement TO app_python;
GRANT SELECT ON TABLE admin.departement TO min_scalingo;
GRANT SELECT ON TABLE admin.departement TO min_dev;


--
-- Name: TABLE epci; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.epci TO app_python;
GRANT SELECT ON TABLE admin.epci TO min_scalingo;
GRANT SELECT ON TABLE admin.epci TO min_dev;


--
-- Name: TABLE region; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.region TO app_python;
GRANT SELECT ON TABLE admin.region TO min_scalingo;
GRANT SELECT ON TABLE admin.region TO min_dev;


--
-- Name: TABLE coll_terr; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.coll_terr TO app_python;


--
-- Name: SEQUENCE commune_epci_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.commune_epci_id_seq TO app_python;


--
-- Name: SEQUENCE commune_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.commune_id_seq TO app_python;


--
-- Name: SEQUENCE departement_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.departement_id_seq TO app_python;


--
-- Name: SEQUENCE epci_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.epci_id_seq TO app_python;


--
-- Name: TABLE ifn_commune; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.ifn_commune TO app_python;


--
-- Name: SEQUENCE ifn_commune_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.ifn_commune_id_seq TO app_python;


--
-- Name: TABLE insee_cp; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.insee_cp TO app_python;
GRANT SELECT ON TABLE admin.insee_cp TO min_scalingo;
GRANT SELECT ON TABLE admin.insee_cp TO min_dev;


--
-- Name: SEQUENCE insee_cp_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.insee_cp_id_seq TO app_python;


--
-- Name: TABLE insee_historique; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.insee_historique TO app_python;
GRANT SELECT ON TABLE admin.insee_historique TO min_scalingo;
GRANT SELECT ON TABLE admin.insee_historique TO min_dev;


--
-- Name: SEQUENCE insee_historique_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.insee_historique_id_seq TO app_python;


--
-- Name: SEQUENCE region_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.region_id_seq TO app_python;


--
-- Name: TABLE zonage; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.zonage TO app_python;
GRANT SELECT ON TABLE admin.zonage TO min_scalingo;
GRANT SELECT ON TABLE admin.zonage TO min_dev;


--
-- Name: SEQUENCE zonage_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.zonage_id_seq TO app_python;


--
-- Name: TABLE zonage_log_erreur; Type: ACL; Schema: admin; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE admin.zonage_log_erreur TO app_python;
GRANT SELECT ON TABLE admin.zonage_log_erreur TO min_scalingo;
GRANT SELECT ON TABLE admin.zonage_log_erreur TO min_dev;


--
-- Name: SEQUENCE zonage_log_erreur_id_seq; Type: ACL; Schema: admin; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE admin.zonage_log_erreur_id_seq TO app_python;


--
-- Name: TABLE adresse; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.adresse TO app_python;
GRANT SELECT ON TABLE main.adresse TO min_scalingo;
GRANT SELECT ON TABLE main.adresse TO min_dev;


--
-- Name: TABLE structure; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.structure TO app_python;
GRANT SELECT ON TABLE main.structure TO min_scalingo;
GRANT SELECT ON TABLE main.structure TO min_dev;


--
-- Name: TABLE categories_juridiques; Type: ACL; Schema: reference; Owner: sonum
--

GRANT SELECT ON TABLE reference.categories_juridiques TO min_scalingo;
GRANT SELECT ON TABLE reference.categories_juridiques TO min_dev;


--
-- Name: TABLE personne; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.personne TO app_python;
GRANT SELECT ON TABLE main.personne TO min_scalingo;
GRANT SELECT ON TABLE main.personne TO min_dev;


--
-- Name: TABLE personne_lieux_activites; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.personne_lieux_activites TO app_python;
GRANT SELECT ON TABLE main.personne_lieux_activites TO min_scalingo;
GRANT SELECT ON TABLE main.personne_lieux_activites TO min_dev;


--
-- Name: TABLE personne_structures_emplois; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.personne_structures_emplois TO app_python;
GRANT SELECT ON TABLE main.personne_structures_emplois TO min_scalingo;
GRANT SELECT ON TABLE main.personne_structures_emplois TO min_dev;


--
-- Name: TABLE activites_coop; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE main.activites_coop TO app_python;
GRANT SELECT ON TABLE main.activites_coop TO min_scalingo;
GRANT SELECT ON TABLE main.activites_coop TO min_dev;


--
-- Name: SEQUENCE activites_coop_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.activites_coop_id_seq TO app_python;


--
-- Name: SEQUENCE adresse_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.adresse_id_seq TO app_python;


--
-- Name: TABLE coordination_mediation; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.coordination_mediation TO app_python;
GRANT SELECT ON TABLE main.coordination_mediation TO min_scalingo;
GRANT SELECT ON TABLE main.coordination_mediation TO min_dev;


--
-- Name: SEQUENCE coordination_mediation_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.coordination_mediation_id_seq TO app_python;


--
-- Name: SEQUENCE personne_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.personne_id_seq TO app_python;


--
-- Name: SEQUENCE personne_lieux_activites_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.personne_lieux_activites_id_seq TO app_python;


--
-- Name: SEQUENCE personne_structures_emplois_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.personne_structures_emplois_id_seq TO app_python;


--
-- Name: TABLE poste; Type: ACL; Schema: main; Owner: sonum
--

GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLE main.poste TO app_python;
GRANT SELECT ON TABLE main.poste TO min_scalingo;
GRANT SELECT ON TABLE main.poste TO min_dev;


--
-- Name: SEQUENCE poste_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.poste_id_seq TO app_python;


--
-- Name: SEQUENCE structure_id_seq; Type: ACL; Schema: main; Owner: sonum
--

GRANT USAGE,UPDATE ON SEQUENCE main.structure_id_seq TO app_python;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: admin; Owner: sonum
--

ALTER DEFAULT PRIVILEGES FOR ROLE sonum IN SCHEMA admin GRANT USAGE,UPDATE ON SEQUENCES TO app_python;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: admin; Owner: sonum
--

ALTER DEFAULT PRIVILEGES FOR ROLE sonum IN SCHEMA admin GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLES TO app_python;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: main; Owner: sonum
--

ALTER DEFAULT PRIVILEGES FOR ROLE sonum IN SCHEMA main GRANT USAGE,UPDATE ON SEQUENCES TO app_python;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: main; Owner: sonum
--

ALTER DEFAULT PRIVILEGES FOR ROLE sonum IN SCHEMA main GRANT SELECT,INSERT,TRIGGER,TRUNCATE,UPDATE ON TABLES TO app_python;


--
-- PostgreSQL database dump complete
--

