-- Revue des appariements de lieux mednum ↔ coop (#1845) : main.lieu_appariement
-- est une table du schéma main portée par Flyway côté dataspace (V152,
-- 2026-08-19), postérieure au dernier snapshot dataspace_integration de MIN.
-- Cette migration ne sert qu'aux bases locales / de test (MIN ne migre plus en
-- prod) : elle reproduit la définition V152 à l'identique. IF NOT EXISTS pour
-- rester rejouable une fois le snapshot régénéré (la table y arrivera alors
-- déjà — même pattern que conum_labellisation / V143).
CREATE TABLE IF NOT EXISTS main.lieu_appariement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carto_segment text NOT NULL,
    lieu_id integer NOT NULL,
    carto_record_id text NOT NULL,
    source text,
    methode varchar(20) NOT NULL
        CHECK (methode IN ('segment_coop', 'similarite')),
    statut varchar(20) NOT NULL DEFAULT 'a_valider'
        CHECK (statut IN ('auto', 'a_valider', 'valide', 'rejete')),
    score_nom smallint,
    score_adresse smallint,
    score_distance smallint,
    score_global smallint,
    distance_m integer,
    carto_nom text,
    carto_adresse text,
    carto_commune text,
    premiere_detection timestamp NOT NULL DEFAULT now(),
    derniere_detection timestamp NOT NULL DEFAULT now(),
    decide_par varchar(255),
    decide_le timestamp,
    CONSTRAINT lieu_appariement_ukey UNIQUE (carto_segment, lieu_id)
);

CREATE INDEX IF NOT EXISTS lieu_appariement_lieu_idx ON main.lieu_appariement (lieu_id);
CREATE INDEX IF NOT EXISTS lieu_appariement_a_valider_idx ON main.lieu_appariement (statut)
    WHERE statut = 'a_valider';
