import { Typologie } from '@gouvfr-anct/lieux-de-mediation-numerique'

// Mapping des codes de typologie (valeurs de main.lieu_inclusion.typologies,
// identiques aux valeurs de l'enum Typologie du référentiel de la médiation
// numérique) vers leurs libellés lisibles. Partagé entre la fiche lieu et la
// liste des lieux, où la typologie native remplace l'ancienne catégorie
// juridique de la structure administrative (#1711).
export const typologieLabels: Readonly<Record<Typologie, string>> = {
  [Typologie.ACI]: "Structures porteuses d'ateliers et chantiers d'insertion",
  [Typologie.ACIPHC]: "SIAE — Atelier chantier d'insertion premières heures en chantier",
  [Typologie.AFPA]: 'Agence nationale pour la formation professionnelle des adultes',
  [Typologie.AI]: 'Associations intermédiaires',
  [Typologie.ASE]: "Aide sociale à l'enfance",
  [Typologie.ASSO]: 'Associations',
  [Typologie.ASSO_CHOMEUR]: 'Associations de chômeurs',
  [Typologie.AUTRE]: 'Autre',
  [Typologie.AVIP]: "Crèche à vocation d'insertion professionnelle",
  [Typologie.BIB]: 'Bibliothèque / Médiathèque',
  [Typologie.CAARUD]: "Centre d'accueil et d'accompagnement à la réduction de risques pour usagers de drogues",
  [Typologie.CADA]: "Centres d'accueil de demandeurs d'asile",
  [Typologie.CAF]: "Caisses d'allocation familiale",
  [Typologie.CAP_EMPLOI]: 'Cap Emploi',
  [Typologie.CAVA]: "Centres d'adaptation à la vie active",
  [Typologie.CC]: 'Communautés de Commune',
  [Typologie.CCAS]: "Centres communaux d'action sociale",
  [Typologie.CCONS]: 'Chambres consulaires',
  [Typologie.CD]: 'Conseils Départementaux',
  [Typologie.CDAS]: "Centre départemental d'action sociale",
  [Typologie.CFP]: 'Centre des finances publiques',
  [Typologie.CHRS]: "Centres d'hébergement et de réinsertion sociale",
  [Typologie.CHU]: "Centres d'hébergement d'urgence",
  [Typologie.CIAS]: "Centres intercommunaux d'action sociale",
  [Typologie.CIDFF]: "Centres d'information sur les droits des femmes et des familles",
  [Typologie.CITMET]: 'Cité des métiers',
  [Typologie.CMP]: 'Centre Médico Psychologique',
  [Typologie.CMS]: 'Centre médico-social',
  [Typologie.CPAM]: "Caisse primaire d'assurance maladie",
  [Typologie.CPH]: "Centres provisoires d'hébergement",
  [Typologie.CS]: 'Centre social',
  [Typologie.CSAPA]: "Centre de soins, d'accompagnement et de prévention en addictologie",
  [Typologie.CSC]: 'Centre socioculturel',
  [Typologie.DEETS]: "Directions de l'Economie, de l'Emploi, du Travail et des Solidarités",
  [Typologie.DEPT]: 'Services sociaux du Conseil départemental',
  [Typologie.DIPLP]: 'Délégation interministérielle à la prévention et à la lutte contre la pauvreté',
  [Typologie.E2C]: 'École de la deuxième chance',
  [Typologie.EA]: 'Entreprise adaptée',
  [Typologie.EATT]: 'Entreprise adaptée',
  [Typologie.EI]: "Entreprises d'insertion",
  [Typologie.EITI]: "Entreprises d'insertion par le travail indépendant",
  [Typologie.ENM]: 'Espace Numérique Mobile',
  [Typologie.EPCI]: 'Intercommunalité',
  [Typologie.EPI]: 'Espace Public Internet',
  [Typologie.EPIDE]: "Établissement pour l'insertion dans l'emploi",
  [Typologie.EPN]: 'Espace publique numérique',
  [Typologie.ES]: 'Épicerie solidaire',
  [Typologie.ESAT]: "Établissements ou services d'aide par le travail",
  [Typologie.ESS]: "Entreprise de l'Économie Sociale et Solidaire",
  [Typologie.ETTI]: "Entreprises de travail temporaire d'insertion",
  [Typologie.EVS]: 'Espace de vie sociale',
  [Typologie.FABLAB]: 'Fablab',
  [Typologie.FABRIQUE]: 'Fabrique',
  [Typologie.FAIS]: "Fédérations d'acteurs de l'insertion et de la solidarité",
  [Typologie.FT]: 'France travail',
  [Typologie.GEIQ]: "Groupements d'employeurs pour l'insertion et la qualification",
  [Typologie.HUDA]: "Hébergement d'urgence pour demandeurs d'asile",
  [Typologie.LA_POSTE]: 'La Poste',
  [Typologie.MDE]: "Maison de l'emploi",
  [Typologie.MDEF]: "Maison de l'emploi et de la formation",
  [Typologie.MDH]: 'Maison des Habitants',
  [Typologie.MDPH]: 'Maison Départementale des Personnes Handicapées',
  [Typologie.MDS]: 'Maison Départementale des Solidarités',
  [Typologie.MJC]: 'Maison des jeunes et de la culture',
  [Typologie.ML]: 'Mission Locale',
  [Typologie.MQ]: 'Maison de quartier',
  [Typologie.MSA]: 'Mutualité Sociale Agricole',
  [Typologie.MSAP]: 'Maison de Services Au Public',
  [Typologie.MUNI]: 'Municipalités',
  [Typologie.OACAS]: "Structures agréées Organisme d'accueil communautaire et d'activité solidaire",
  [Typologie.ODC]: "Organisation délégataire d'un CD",
  [Typologie.OF]: 'Organisme de formations',
  [Typologie.OIL]: "Opérateur d'intermédiation locative",
  [Typologie.OPCS]: 'Organisation porteuse de la clause sociale',
  [Typologie.PAD]: "Point d'Accès au Droit",
  [Typologie.PENSION]: 'Pension de famille',
  [Typologie.PI]: 'Point info',
  [Typologie.PIJ_BIJ]: 'Points et bureaux information jeunesse',
  [Typologie.PIMMS]: 'Point Information Médiation Multi Services',
  [Typologie.PJJ]: 'Protection judiciaire de la jeunesse',
  [Typologie.PLIE]: "Plans locaux pour l'insertion et l'emploi",
  [Typologie.PREF]: 'Préfecture, Sous-Préfecture',
  [Typologie.PREVENTION]: 'Service ou club de prévention',
  [Typologie.REG]: 'Région',
  [Typologie.RELAIS_LECTURE]: 'Relais lecture',
  [Typologie.RESSOURCERIE]: 'Ressourcerie',
  [Typologie.RFS]: 'Réseau France Services',
  [Typologie.RS_FJT]: 'Résidence sociale - Foyer de Jeunes Travailleurs',
  [Typologie.SCP]: 'Services et clubs de prévention',
  [Typologie.SPIP]: "Services pénitentiaires d'insertion et de probation",
  [Typologie.TIERS_LIEUX]: 'Tiers lieu & coworking',
  [Typologie.UDAF]: "Union Départementale d'Aide aux Familles",
}

// Libellé d'affichage d'un lieu à partir de sa première typologie. Renvoie
// « Non renseigné » si absente ou hors référentiel.
export function libelleTypologie(code: null | string | undefined): string {
  if (code != null && code in typologieLabels) {
    return typologieLabels[code as Typologie]
  }
  return 'Non renseigné'
}
